# Taking Ubuntu 12.04 as base image for the deployment
FROM ubuntu:12.04

# Update apt source list
RUN apt-get -y update

# Installing required system components
RUN apt-get -y install python-software-properties

# Adding redis repository
RUN apt-add-repository -y ppa:rwky/redis

# Update apt source list
RUN apt-get -y update

# Installing redis
RUN apt-get install redis-server

# Binding redis port to external network
EXPOSE 6379

# We'll print local ip assigned to container
# and start the redis
ENTRYPOINT ifconfig && redis-server